global using Ardalis.GuardClauses;
global using AutoMapper;
global using AutoMapper.QueryableExtensions;
global using Microsoft.EntityFrameworkCore;
global using FluentValidation;
global using MediatR;
global using AttendanceMaSys.Domain.Common;
global using AttendanceMaSys.Domain.Entities;
global using AttendanceMaSys.Domain.Enums;